# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Libary.ui'
#
# Created by: PyQt UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2 import QtCore, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.libary_tree = QtWidgets.QTreeWidget(Dialog)
        self.libary_tree.setObjectName("libary_tree")
        self.horizontalLayout.addWidget(self.libary_tree)
        self.view = QtWidgets.QTextBrowser(Dialog)
        self.view.setObjectName("view")
        self.horizontalLayout.addWidget(self.view)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Dialog_2 = QtWidgets.QDialogButtonBox(Dialog)
        self.Dialog_2.setOrientation(QtCore.Qt.Horizontal)
        self.Dialog_2.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Dialog_2.setObjectName("Dialog_2")
        self.verticalLayout.addWidget(self.Dialog_2)

        self.retranslateUi(Dialog)
        self.Dialog_2.accepted.connect(Dialog.accept)
        self.Dialog_2.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Libary of SpaceBox Bodys</span></p></body></html>"))
        self.libary_tree.headerItem().setText(0, _translate("Dialog", "Parts"))
